### ISSUE TITLE
SQL batch mode exception

### ISSUE THREAD

**Issue by marksilvis** [bd2kccd/ccd-annotations-cytoscape#45]
When opening Cytoscape and starting a new session with an empty network I receive an `SQLException` due to the statement not being in batch mode.

Here is the entire stack trace:
```java
java.sql.SQLException: statement is not in batch mode
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlExceptionSQL(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeBatch(Unknown Source)
	at edu.pitt.cs.admt.cytoscape.annotations.db.StorageDelegate.insertNodes(StorageDelegate.java:139)
	at edu.pitt.cs.admt.cytoscape.annotations.db.NetworkStorageUtility.importToDatabase(NetworkStorageUtility.java:22)
	at edu.pitt.cs.admt.cytoscape.annotations.network.NetworkListener.handleEvent(NetworkListener.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.cytoscape.event.internal.CyListenerAdapter.fireEvent(CyListenerAdapter.java:120)
	at org.cytoscape.event.internal.CyEventHelperImpl.fireEvent(CyEventHelperImpl.java:84)
	at org.cytoscape.view.model.internal.CyNetworkViewManagerImpl.fireEvent(CyNetworkViewManagerImpl.java:204)
	at org.cytoscape.view.model.internal.CyNetworkViewManagerImpl.addNetworkView(CyNetworkViewManagerImpl.java:193)
	at org.cytoscape.view.model.internal.CyNetworkViewManagerImpl.addNetworkView(CyNetworkViewManagerImpl.java:164)
	at org.cytoscape.task.internal.creation.NewEmptyNetworkTask.run(NewEmptyNetworkTask.java:205)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:326)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:355)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.hsqldb.HsqlException: statement is not in batch mode
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	... 22 more
```

**Comment by marksilvis** [comment]
Fixed
